### ISSUE TITLE
ESPECIFICACIONES DE REQUERIMIENTOS_Abigail Coronel Santiago

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo_judith#4]
[GESTION Y VALIDACION DE DATOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo_judith/files/10070954/GESTION.Y.VALIDACION.DE.DATOS.pdf)

**Comment by Elisahadad** [comment]
30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
